title = "Feedback Realisatie Experimenten Automatisering Konfiguratie"

[data]
created = 2022-01-07T15:40:18.951037

[students.PelikaanSteven]
FirstName = "Steven"
MiddleName = " "
LastName = "Pelikaan"

[students.StudentTest]
FirstName = "Test"
MiddleName = " "
LastName = "Student"
