title = "Feedback Realisatie Experimenten Automatisering Konfiguratie"

[data]
created = 2022-02-01T12:08:15.977346
update = 2022-02-01T12:19:56.522544
"last update" = 2022-02-01T12:28:08.175215

[feedback]
" PelikaanSteven" = [ "CLASSES01",]
" VorstvanderKaatje" = [ "VARNAME01",]
" JohnElton" = [ "VARNAME01", "CLASSES01",]

[students." PelikaanSteven"]
FirstName = "Steven"
ID = 123456

[students." VorstvanderKaatje"]
FirstName = "Kaatje"
ID = 1535013

[students." JohnElton"]
FirstName = "Elton"
ID = 98720
