title = "Feedback Realisatie Experimenten Automatisering Konfiguratie"

[data]
created = 2022-01-31T17:07:43.352203

[feedback]
" JohnElton" = [ "VARNAME01", "CLASSES01",]

[students." PelikaanSteven"]
FirstName = "Steven"
ID = 123456

[students." VorstvanderKaatje"]
FirstName = "Kaatje"
ID = 1535013

[students." JohnElton"]
FirstName = "Elton"
ID = 98720
