title = "Feedback Realisatie Experimenten Automatisering Konfiguratie"

[data]
created = 2022-02-01T12:08:15.977346

[feedback]
" PelikaanSteven" = [ "VARNAME01", "CLASSES01",]
" VorstvanderKaatje" = [ "VARNAME01", "CLASSES01",]
" JohnElton" = []

[students." PelikaanSteven"]
FirstName = "Steven"
ID = 123456

[students." VorstvanderKaatje"]
FirstName = "Kaatje"
ID = 1535013

[students." JohnElton"]
FirstName = "Elton"
ID = 98720
