title = "Feedback Realisatie Experimenten Automatisering Konfiguratie"

[data]
created = 2022-05-23T17:07:05.906404
"last update" = 2022-08-01T10:51:27.516842

[students." PelikaanSteven"]
FirstName = "Steven"
ID = 123456

[students." VorstvanderKaatje"]
FirstName = "Kaatje"
ID = 1535013

[students." JohnElton"]
FirstName = "Elton"
ID = 98720

[feedback.checkbox]
" PelikaanSteven" = [ "CLASSES01",]
" VorstvanderKaatje" = []
" JohnElton" = []

[feedback.annotations]
" PelikaanSteven" = [ "Zal het nog steeds werken?", "ik hoop het",]
" VorstvanderKaatje" = [ "Ik hoop het wel ", "",]
" JohnElton" = []
