title = "Feedback Realisatie Experimenten Automatisering Konfiguratie"

[data]
created = 2022-01-31T15:45:20.803071

[students." PelikaanSteven"]
FirstName = "Steven"
ID = 123456

[students." VorstvanderKaatje"]
FirstName = "Kaatje"
ID = 1535013

[students." JohnElton"]
FirstName = "Elton"
ID = 98720
