title = "Feedback Realisatie Experimenten Automatisering Konfiguratie"

[data]
created = 2022-05-12T19:56:25.889652
"last update" = 2022-05-12T20:04:43.448929

[feedback]
" PelikaanSteven" = [ "VARNAME01", "CLASSES01",]
" VorstvanderKaatje" = [ "VARNAME01",]
" JohnElton" = []

[students." PelikaanSteven"]
FirstName = "Steven"
ID = 123456

[students." VorstvanderKaatje"]
FirstName = "Kaatje"
ID = 1535013

[students." JohnElton"]
FirstName = "Elton"
ID = 98720
