title = "Feedback Realisatie Experimenten Automatisering Konfiguratie"

[data]
created = 2022-09-26T16:30:23.977145
"last update" = 2022-09-26T16:31:16.698318

[students."(2691938)"]
first_name = "Marrit"
last_name = "Adema"
full_name = "Marrit Adema"

[students."(2744675)"]
first_name = "Farah"
last_name = "Adouti"
full_name = "Farah Adouti"

[students."(2766801)"]
first_name = "Niels"
last_name = "Baan"
full_name = "Niels Baan"

[students."(2785919)"]
first_name = "Dana"
last_name = "van Beem"
full_name = "Dana van Beem"

[students."(2784840)"]
first_name = "Pepijn"
last_name = "Beentjes"
full_name = "Pepijn Beentjes"

[students."(1234567)"]
first_name = "Anne-Lotte"
last_name = "Ruhl"
full_name = "Anne-Lotte Ruhl"

[feedback.checkbox]
"(2691938)" = []
"(2744675)" = []
"(2766801)" = []
"(2785919)" = []
"(2784840)" = []
"(1234567)" = []

[feedback.annotations]
"(2691938)" = []
"(2744675)" = []
"(2766801)" = []
"(2785919)" = []
"(2784840)" = []
"(1234567)" = []
