title = "Feedback Realisatie Experimenten Automatisering Konfiguratie"

[data]
created = 2022-02-01T12:35:26.411208
"last update" = 2022-02-01T12:53:29.988929

[feedback]
" PelikaanSteven" = [ "VARNAME01", "CLASSES01",]
" VorstvanderKaatje" = [ "CLASSES01",]
" JohnElton" = [ "VARNAME01", "CLASSES01",]

[students." PelikaanSteven"]
FirstName = "Steven"
ID = 123456

[students." VorstvanderKaatje"]
FirstName = "Kaatje"
ID = 1535013

[students." JohnElton"]
FirstName = "Elton"
ID = 98720
