title = "Feedback Realisatie Experimenten Automatisering Konfiguratie"

[data]
created = 2022-05-23T16:16:56.287912
"last update" = 2022-05-23T16:35:24.040851

[students." PelikaanSteven"]
FirstName = "Steven"
ID = 123456

[students." VorstvanderKaatje"]
FirstName = "Kaatje"
ID = 1535013

[students." JohnElton"]
FirstName = "Elton"
ID = 98720

[feedback.checkbox]
" PelikaanSteven" = [ "VARNAME01",]
" VorstvanderKaatje" = [ "CLASSES01",]
" JohnElton" = []

[feedback.annotations]
" PelikaanSteven" = [ "Je kan hier iets typen", "Maar we zien nog niks veranderen ",]
" VorstvanderKaatje" = [ "", "",]
" JohnElton" = [ "En als ik nu hier iets type", "Dan is het wel een beetje anders. ",]
